language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'

before_script:
  - composer install
  - mkdir build/logs -p

script:
  - ./vendor/bin/php-cs-fixer fix -v --dry-run
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
