language: php
php:
  - '7.1'
  - '7.2'

before_script:
  - composer install

script:
  - vendor/bin/php-cs-fixer fix -v --dry-run
  - phpunit --coverage-clover build/logs/clover.xml
  - vendor/bin/doc2test && vendor/bin/phpunit -c doc-test/phpunit.xml
